package Utilities;

enum COMMITTEE {
    AGRICULTURE,
    APPROPRIATIONS,
    ARMEDSERVICES,
    CONGRESSIONALEXECUTIVECOMMISSIONONCHINA,
    EDUCATION,
    ENERGYANDCOMMERCE,
    FINANCIALSERVICES,
    FOREIGNAFFAIRS,
    HOMELANDSECURITY,
    HOUSE,
    NATURALRESOURCES,
    OVERSIGHT,
    SCIENCESPACEANDTECHNOLOGY,
    SMALLBUSINESS,
    TRANSPORTATIONANDINFRASTRUCTURE,
    VETERANSAFFAIRS,
    WAYSANDMEANS,
    THEBUDGET,
    THEJUDICIARY,


}
